USE [Phonebook]
GO

/****** Object:  Table [dbo].[Entry]    Script Date: 2021/07/20 10:59:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Entry](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PhonebookID] [int] NULL,
	[Name] [varchar](100) NULL,
	[PhoneNumber] [nchar](100) NULL,
 CONSTRAINT [PK_Entry] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Entry]  WITH CHECK ADD  CONSTRAINT [FK_Entry_Phonebook] FOREIGN KEY([PhonebookID])
REFERENCES [dbo].[Phonebook] ([ID])
GO

ALTER TABLE [dbo].[Entry] CHECK CONSTRAINT [FK_Entry_Phonebook]
GO


